const LocationActionTypes = {
  FETCH_CITY_START: 'FETCH_CITY_START',
  FETCH_CITY_SUCCESS: 'FETCH_CITY_SUCCESS',
  FETCH_CITY_FAILURE: 'FETCH_CITY_FAILURE',
  FETCH_STATE_START: 'FETCH_STATE_START',
  FETCH_STATE_SUCCESS: 'FETCH_STATE_SUCCESS',
  FETCH_STATE_FAILURE: 'FETCH_STATE_FAILURE'
};

export default LocationActionTypes;
