const programmingLanguages = [
  'ADO.NET ',
  'APL ',
  'ASIC Programming Language',
  'AWK ',
  'Ada ',
  'Agilent VEE (Domain-Specific Programming Language)',
  'Ajax ',
  'Algebraic Logic Functional [Programming Language]',
  'Are we missing something? Suggest a skill!',
  'B ',
  'Blitz BASIC (Object-Oriented Programming Language)',
  'C ',
  'C Data Types (C Programming Language)',
  'C# ',
  'C++ ',
  'C-Based Programming Languages',
  'COBOL ',
  'Communication Program Generator ',
  'DATABUS ',
  'DarkBASIC ',
  'Delphi ',
  'E ',
  'ECMAScript (C Programming Language Family)',
  'Elixir ',
  'Eltron Programming Language',
  'Event Programming Language',
  'F# ',
  'FOIL ',
  'Fifth-Generation Programming Languages',
  'First-Generation Programming Languages',
  'Forth ',
  'Fortran ',
  'Fourth-Generation Programming Language',
  'G Programming Language',
  'GNU Cflow (C Programming Language)',
  'Go ',
  'Groovy ',
  'High Performance Fortran (Concurrent Programming Language)',
  'IBM RPG ',
  'Java ',
  'JavaScript ',
  'Javac - Java Programming Language Compiler',
  'KM Programming Language',
  'Lasso ',
  'Lisp ',
  'Low-Level Programming Language',
  'M ',
  'MISRA C (C Programming Language)',
  'Microsoft Visual Programming Language',
  'New Executive Programming Language (NEWP)',
  'Object Oriented Programming Language',
  'Objective-C ',
  'Ocaml ',
  'Open Programming Language',
  'Open-Source Programming Languages',
  'PALASM ',
  'PL/I (Procedural Programming Language)',
  'Pascal ',
  'Perl ',
  'PowerHouse ',
  'Programming Language Benchmarks',
  'Programming Language For Business',
  'Programming Language Theory',
  'Python ',
  'R ',
  'RPL ',
  'Racket ',
  'RainCode PL/1 (Procedural Programming Language)',
  'Rexx ',
  'Ruby ',
  'S/SL Programming Language',
  'SQL ',
  'Sather ',
  'Scala ',
  'Scheme ',
  'Sed ',
  'Smalltalk ',
  'Swift ',
  'System Programming Language',
  'TACPOL ',
  'TTCN ',
  'Tcl ',
  'The BitC Programming Language',
  'Unisys MCP Programming Languages',
  'Vala ',
  'Visual Basic ',
  'Visual Basic .NET ',
  'Visual C++ ',
  'Visual Programming Language (VPL)',
  'X++ ',
  'XML-Based Programming Languages',
  'XPC Target (Simulation Programming Language)',
  'Zonnon '
];

const Database = [
  '4d Database',
  'ADOdb Database Abstraction Library For PHP',
  'Accession Commitments Database',
  'Active Database Management Systems',
  'Advantage Database Servers',
  'Aerodrome Mapping Databases',
  'Amazon Relational Database Services',
  'Are we missing something? Suggest a skill!',
  'Basis Database',
  'Beilstein Database',
  'Bibliographic Databases',
  'Bioinformatics Databases',
  'Biological Database',
  'Borland Database Engine',
  'CIW V5 Database Design Specialists',
  'Certified MySQL Database Administrator',
  'Chemical Databases',
  'Cloud Database',
  'Component-Oriented Databases',
  'Configuration Management Databases',
  'Consensus CDS Project (Biological Databases)',
  'Consumer Database Management System',
  'Correlation Database',
  'DNA Databases',
  'DataBase Markup Language',
  'DataBase Of CpG Islands And Analytical Tool',
  'Database Abstraction Layer',
  'Database Administration',
  'Database Analysis',
  'Database Application',
  'Database Audit',
  'Database Availability Group',
  'Database Cluster',
  'Database Comparison',
  'Database Connection',
  'Database Consistency',
  'Database Deployment Management',
  'Database Design',
  'Database Development',
  'Database Diagram',
  'Database Directive',
  'Database Dump',
  'Database Encryption',
  'Database Engine Tuning Advisor',
  'Database Engines',
  'Database First',
  'Database Independent',
  'Database Indexes',
  'Database Life Cycle',
  'Database Management Systems',
  'Database Marketing',
  'Database Mirroring',
  'Database Models',
  'Database Normalization',
  'Database Partitioning',
  'Database Performance Analyzer',
  'Database Permissions',
  "Database Programmer's Toolkits",
  'Database Publishing',
  'Database Queries',
  'Database Query Language For Enterprise Java Beans (EJB-QL)',
  'Database Scan',
  'Database Schema',
  'Database Search Engine',
  'Database Security',
  'Database Servers',
  'Database Storage Structures',
  'Database Systems',
  'Database Testing',
  'Database Theory',
  'Database Transactions',
  'Database Triggers',
  'Database Tuning',
  'Database Virtualization',
  'DeZign For Databases',
  'Deductive Database',
  'Distributed Database',
  'Distributed Database Management System (DDBMS)',
  'Distributed Relational Database Architecture (DRDA)',
  'Document-Oriented Databases',
  'DrugBank Database',
  'Embedded Databases',
  'Federated Database Systems',
  'Firebird Database',
  'Flat File Database',
  'Foglight (Database Software)',
  'Geospatial Databases',
  'Graph Database',
  'Hierarchical Database Model',
  'Hyper SQL Database (HSQLDB)',
  'IBM - IMS High Availability Large Database',
  'IBM - Tivoli Change And Configuration Management Database',
  'In-Memory Database',
  'Integrated Archaeological Databases',
  'Integrated Database Application Program Interface (IDAPI)',
  'Java Database Connectivity',
  'Logical Databases',
  'Mantis Databases',
  'Materials Databases',
  'Medicines Quality Database',
  'Microsoft Certified Database Administrator',
  'Molecular Modeling Database',
  'Msdb Database',
  'Multidimensional Database',
  'Multidimensional Database Management Systems',
  'NMR Spectra Database',
  'National Soil DataBase',
  'Navigational Database',
  'New Database Manager (NDBM)',
  'ODQL - Object Database Query Language',
  'Object Databases',
  'Object Linking And Embedding - Database (OLE DB)',
  'Object-Oriented Data Model For Database Modelling',
  'Object-Oriented Database',
  'Object-Relational Database',
  'Online Databases',
  'Online Music Databases',
  'Open Database Connectivity',
  'Operational Databases',
  'Oracle Certified Associate Database Administrator',
  'Oracle Certified Professional Database Administrator',
  'Oracle Database 11g Administrator Certified Associate',
  'Oracle Databases',
  'Program Database',
  'Protein Database',
  'Raima Database Management',
  'Relational Database Management Systems',
  'Relational Databases',
  'Remote Database Access',
  'Routing Assets Databases',
  'Saccharomyces Genome Databases',
  'Shard (Database Architecture)',
  'Simple Object Database Access',
  'Single Nucleotide Polymorphism Database[1] (DbSNP)',
  'Spatial Databases',
  'Superbase Database',
  'Text Database',
  'UniProt (Biological Databases)',
  'Universal Database (UDB)',
  'Versant Object Database',
  'Web SQL Databases',
  'XML Databases',
  'Zope Object Databases'
];

export const skillData = [...programmingLanguages, ...Database].sort();
