const CandidateActionTypes = {
  TOGGLE_CANDIDATE_HIDDEN: 'TOGGLE_CANDIDATE_HIDDEN',
  FETCH_EXISTING_CANDIDATE_SUCCESS: 'FETCH_EXISTING_CANDIDATE_SUCCESS',
  CREATE_CANDIDATE_SUCCESS: 'CREATE_CANDIDATE_SUCCESS',
  UPDATE_CANDIDATE_SUCCESS: 'UPDATE_CANDIDATE_SUCCESS',
  REMOVE_CANDIDATE: 'REMOVE_CANDIDATE'
};

export default CandidateActionTypes;
